name: CI Dev
on:
  push:
    branches:
      - dev
jobs:
  CI-dev:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Install CUPS (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcups2-dev build-essential python-is-python3 gcc g++ make python3-dev

      - name: Configurar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependências
        run: npm install --no-save

      - name: Rebuild do projeto
        run: npm run rebuild
