name: CI Master

on:
  push:
    branches:
      - master

jobs:
  CI-master:
    runs-on: windows-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Configurar Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Instalar dependências
        run: npm install --no-save
      
      - name: Pre Build node x64
        run: npm run prebuild:action -- --strip -t 18.20.6 -t 19.0.0 -t 20.0.0 -t 21.0.0 -t 22.0.0 -a x64 -u ${{ secrets.GH_TOKEN }}
      
      - name: Pre Build node ia32
        run: npm run prebuild:action -- --strip -t 18.20.6 -t 19.0.0 -t 20.0.0 -t 21.0.0 -t 22.0.0 -a ia32 -u ${{ secrets.GH_TOKEN }}
      
      - name: Pre Build Electron x64
        run: npm run prebuild:action -- --strip -t 20.0.0 -t 21.0.0 -t 22.0.0 -t 23.0.0 -t 24.0.0 -t 25.0.0 -t 26.0.0 -t 27.0.0 -t 28.0.0 -t 29.0.0 -t 30.0.0 -t 31.0.0 -t 32.0.0 -t 33.0.0 -t 34.0.0 -r electron -a x64 -u ${{ secrets.GH_TOKEN }}
      
      - name: Pre Build Electron ia32
        run: npm run prebuild:action -- --strip -t 20.0.0 -t 21.0.0 -t 22.0.0 -t 23.0.0 -t 24.0.0 -t 25.0.0 -t 26.0.0 -t 27.0.0 -t 28.0.0 -t 29.0.0 -t 30.0.0 -t 31.0.0 -t 32.0.0 -t 33.0.0 -t 34.0.0 -r electron -a ia32 -u ${{ secrets.GH_TOKEN }}
